#!/usr/bin/env bash
# Displays "Best School" 10 times using a while loop and
# on the 9th iteration, it displays "Hi" before "Best School".

counter=1

while [ $counter -le 10 ]
do
	if [ $counter -eq 10 ]
	then
		echo "Hi"
	fi
	echo "Best School"
	(( counter++ ))
done
